# Documentation: https://github.com/actions/labeler

test:
  - changed-files:
    - any-glob-to-any-file: src/**/*.spec.js

ci:
  - changed-files:
    - any-glob-to-any-file: .github/**

documentation:
  - changed-files:
    - any-glob-to-any-file: "**/*.md"

sandbox:
  - changed-files:
    - any-glob-to-any-file: sandbox/**
