name: Labeler

on:
  - pull_request_target
  - workflow_dispatch

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          allowed-endpoints: >
            api.github.com:443
            github.com:443
          disable-sudo: true
          disable-telemetry: true
          egress-policy: block
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
