name: Labeler

on: [pull_request_target]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          disable-sudo: true
          disable-telemetry: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            api.github.com:443
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
