name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string that is used for publishing (e.g. "1.0.0", NOT "v1.0.0").'
        required: true
        type: string

env:
  VERSION: ${{ github.event.inputs.version || inputs.version }}

jobs:
  release:
    permissions:
      contents: write # for softprops/action-gh-release to create the release
      id-token: write # for npm publish with --provenance
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            registry.npmjs.org:443
          disable-sudo: true
          disable-telemetry: false
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: "*" # will get the latest [locally-cached Node.js version](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#nodejs), or the latest version from actions/node-versions
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bump package version
        run: npm version --no-git-tag-version ${{ env.VERSION }}

      - name: Build
        run: npm build

      - name: Commit package version
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Release version ${{ env.npm_package_version }}"

      - name: Create Git tag and GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            LICENSE
          tag_name: v${{ env.npm_package_version }}
          prerelease: false
          fail_on_unmatched_files: true

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
